# Generated by Django 5.2.2 on 2025-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='karat',
            field=models.CharField(choices=[('18K', '18 Karat'), ('22K', '22 Karat'), ('24K', '24 Karat')], default='22K', max_length=10),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in grams', max_digits=6),
        ),
    ]
