# Generated by Django 5.2.2 on 2025-12-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jewellery_karat_jewellery_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
