# Generated by Django 5.2.2 on 2025-12-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subheading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
