# Generated by Django 5.2.2 on 2025-12-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_button_text_alter_banner_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
