# Generated by Django 5.2.2 on 2025-12-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_banner_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page')], default='home', max_length=20),
        ),
    ]
