# Generated by Django 5.2.2 on 2025-12-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_banner_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='occasion',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('party', 'Party'), ('festival', 'Festival')], max_length=20, null=True),
        ),
    ]
