# Generated by Django 5.2.2 on 2025-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jewellery_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='occasion',
        ),
        migrations.AddField(
            model_name='jewellery',
            name='type',
            field=models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace'), ('earring', 'Earring'), ('bracelet', 'Bracelet')], default='ring', max_length=20),
        ),
    ]
