# Generated by Django 5.2.2 on 2025-12-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_jewellery_occasion_jewellery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBelowBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='home_below_banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='type',
            field=models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace'), ('earring', 'Earring'), ('bracelet', 'Bracelet'), ('bangles', 'Bangles')], default='ring', max_length=20),
        ),
    ]
