# Generated by Django 5.2.2 on 2025-12-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homebelowbanner_alter_jewellery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('box_image', models.ImageField(upload_to='occasion/box/')),
                ('model_image', models.ImageField(upload_to='occasion/model/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
