# Generated by Django 5.2.2 on 2025-12-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_occasionbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OccasionBox',
        ),
    ]
