# Generated by Django 5.2.2 on 2026-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_registeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='u_id',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
