# Generated by Django 5.2.2 on 2026-02-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_registeruser_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('silver_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
