# Generated by Django 5.2.1 on 2026-02-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_metalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jewellery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jewellery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registeruser')),
            ],
            options={
                'unique_together': {('user', 'jewellery')},
            },
        ),
    ]
