# Generated by Django 5.2.2 on 2026-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_catalog_wishlistitem_moved_to_cart_jewellery_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='HomeBelowBanner',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='moved_to_cart',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
