# Generated by Django 5.2.2 on 2026-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_jewellery_catalog_delete_homebelowbanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='moved_to_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='karat',
            field=models.CharField(choices=[('22K', '22 Karat'), ('24K', '24 Karat')], default='22K', max_length=10),
        ),
    ]
