# Generated by Django 5.2.2 on 2026-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_wishlistitem_moved_to_cart_alter_jewellery_karat'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='metal_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=10),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='karat',
            field=models.CharField(choices=[('22K', '22 Karat'), ('24K', '24 Karat'), ('NA', 'Not Applicable (For Silver)')], default='22K', max_length=10),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
