# Generated by Django 5.2.2 on 2026-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_jewellery_is_in_stock_jewellery_metal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='metal_type',
        ),
        migrations.AddField(
            model_name='jewellery',
            name='manual_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per gram (Applicable for non-gold/silver items)', max_digits=10),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='material_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('others', 'Others')], default='gold', max_length=20),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='karat',
            field=models.CharField(choices=[('22K', '22 Karat'), ('24K', '24 Karat'), ('NA', 'Not Applicable')], default='22K', max_length=10),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Weight in grams (Use Carats for Diamond/Ruby weight equivalent in grams)', max_digits=10),
        ),
    ]
