# Generated by Django 5.2.2 on 2026-04-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='910000000000', help_text='Enter WhatsApp number with country code (e.g., 919876543210)', max_length=20)),
            ],
        ),
    ]
