# Generated by Django 5.2.2 on 2026-04-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='goldapi_key',
            field=models.CharField(blank=True, help_text='Get your free API key from goldapi.io', max_length=100, null=True),
        ),
    ]
