# Generated by Django 6.0.2 on 2026-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
