# Generated by Django 5.2.2 on 2026-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_registeruser_address_registeruser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
