# Generated by Django 5.2.2 on 2026-04-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
    ]
