# Generated by Django 5.2.2 on 2026-04-19 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_id', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('items_data', models.JSONField(default=list)),
                ('reason', models.CharField(default='Customer requested cancellation', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registeruser')),
            ],
        ),
    ]
