# Generated by Django 5.2.2 on 2026-04-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_cancelledorder_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cancelledorder',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='cancelledorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
