# Generated by Django 5.2.2 on 2026-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='making_charge_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount to apply on the 3% making charges (e.g. 50.00 for 50% off)', max_digits=5),
        ),
    ]
