# Generated by Django 5.2.2 on 2026-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_cancelledorder_discount_amount_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='making_charge_discount_percent',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_making_charge_percent',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Set the making charge percentage for the entire site (default is 3.00)', max_digits=5),
        ),
    ]
