# Generated by Django 5.2.2 on 2026-04-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_sitesetting_making_charge_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='collection_name',
            field=models.CharField(blank=True, default='VIRA', help_text='Collection name for background typography', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='description',
            field=models.TextField(blank=True, help_text='Story and craftsmanship details for the editorial section', null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='era_tag',
            field=models.CharField(blank=True, default="1920's", help_text="Design era for background typography (e.g., 1920's)", max_length=50, null=True),
        ),
    ]
