# Generated by Django 5.2.2 on 2026-04-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_jewellery_collection_name_jewellery_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
