# Generated by Django 5.2.2 on 2026-04-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_jewellery_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='collection_name',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='era_tag',
        ),
    ]
