# Generated by Django 5.2.2 on 2026-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_jewellery_collection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
