# Generated by Django 5.2.2 on 2026-05-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_jewellery_is_best_seller_jewellery_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewellery/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='main.jewellery')),
            ],
        ),
    ]
