# Generated by Django 5.2.2 on 2026-05-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_jewelleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JewelleryImage',
        ),
    ]
