# Generated by Django 5.2.2 on 2026-05-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_jewelleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jewellery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registeruser')),
            ],
        ),
    ]
